import type { MetadataRoute } from "next";

import { APP_NAME, APP_TAGLINE } from "@/utils/utils";

/**
 * PWA manifest.
 *
 * Icons are the raster derivatives of `app/icon.svg`, generated by
 * `brand/generate-icons.mjs`. Only files that exist are listed here — a manifest
 * pointing at missing artwork is worse than a sparse one.
 */
const manifest = (): MetadataRoute.Manifest => ({
  name: `${APP_NAME} — ${APP_TAGLINE}`,
  short_name: APP_NAME,
  description: APP_TAGLINE,
  start_url: "/",
  display: "standalone",
  background_color: "#ffffff",
  theme_color: "#191919",
  icons: [
    {
      src: "/icons/icon-192.png",
      sizes: "192x192",
      type: "image/png",
      purpose: "any",
    },
    {
      src: "/icons/icon-512.png",
      sizes: "512x512",
      type: "image/png",
      purpose: "any",
    },
    {
      src: "/icons/icon-512-maskable.png",
      sizes: "512x512",
      type: "image/png",
      purpose: "maskable",
    },
  ],
});

export default manifest;